# Generated by Django 4.1.7 on 2023-03-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customauth", "0002_useraccount_is_active_useraccount_is_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(
                max_length=60, null=True, unique=True, verbose_name="Email"
            ),
        ),
    ]
