# Generated by Django 4.1.7 on 2023-03-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customauth", "0004_remove_useraccount_username_alter_useraccount_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
