# Generated by Django 4.1.7 on 2023-03-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customauth", "0006_useraccount_usermoney"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("stock_name", models.CharField(max_length=100)),
                ("stock_originalprice", models.IntegerField()),
                ("stock_user", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
