# Generated by Django 4.1.7 on 2023-04-01 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customauth", "0008_stock_delete_stocks"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_name", models.CharField(default="Bitcoin", max_length=100)),
                (
                    "stock_user_email",
                    models.EmailField(
                        default="a@gmail.com",
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="stock",
            name="cnt",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_originalprice",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_status",
            field=models.CharField(default="Bitcoin", max_length=100),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="usermoney",
            field=models.FloatField(default=1000000.0),
        ),
    ]
